# Generated by Django 2.2 on 2021-07-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumers', '0002_auto_20210720_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
