# Generated by Django 2.2 on 2021-07-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumers', '0003_auto_20210720_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='gasValue',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='leakagecase',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='residence',
        ),
    ]
