# Generated by Django 2.2 on 2021-07-20 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Consumers', '0004_auto_20210720_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='consumer',
            name='gasValue',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='consumer',
            name='leakagecase',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='consumer',
            name='residence',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
