# Generated by Django 2.2 on 2021-07-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consumers', '0005_auto_20210720_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='date',
        ),
    ]
