# Generated by Django 2.2 on 2021-07-20 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Consumers', '0006_remove_consumer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
